package hello;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

//Extend the CrudRepository interface, which contains methods for creation, deletion and retrieval
//of entities
public interface ParticleRepository extends CrudRepository<Particle, Long> {

    //Add some simple mysql queries to the repository, these autogenerated functions are called
    //by functions which receives requests in the main controller
    @Query(value = "SELECT * FROM particle WHERE " +
            "LOWER(name) LIKE LOWER(CONCAT('%',:searchTerm, '%')) OR " +
            "LOWER(name) LIKE LOWER(CONCAT('%',:searchTerm, '%'))", nativeQuery = true)
    Iterable<Particle> findByName(@Param("searchTerm") String searchTerm);

    @Query(value = "SELECT * FROM particle WHERE " +
            "mass > :mass", nativeQuery = true)
    Iterable<Particle> findByMassGtr(@Param("mass") double mass);

    @Query(value = "SELECT * FROM particle WHERE " +
            "mass < :mass", nativeQuery = true)
    Iterable<Particle> findByMassLess(@Param("mass") double mass);

    @Query(value = "SELECT * FROM particle WHERE " +
            "charge = :charge", nativeQuery = true)
    Iterable<Particle> findByCharge(@Param("charge") double charge);

}
